/****** Script for SelectTopNRows command from SSMS  ******/
INSERT INTO [SWFIntegrationCore].[dbo].[Tbl_PolizasVehiculos](
      [CodCorredor]
      ,[IdItem]
      ,[IdPoliza]
      ,[NroCertificado]
      ,[FechaAlta]
      ,[CodMarca]
      ,[CodModelo]
      ,[AcreedorHipotecarioLeasing]
      ,[AcreedorHipotecario]
      ,[NombreConductor]
      ,[NombrePropietario]
      ,[SumaAsegurada]
      ,[CodTipoVehiculo]
      ,[TipoVehiculo]
      ,[CantidadOcupantes]
      ,[PrimaBruta]
      ,[PorcImpuesto]
      ,[Impuesto]
      ,[Descuento]
      ,[PrimaNeta]
      ,[IdCompania]
      ,[IdEndoso]
      ,[FechaCreacion]
      ,[EstadoVehiculo]
      ,[AnoVehiculo]
      ,[Marca]
      ,[Modelo]
      ,[SerialMotor]
      ,[SerialCarroceria]
      ,[Color]
      ,[Placa]
      ,[CodPlan]
      ,[RevPlan]
      ,[PrimaBrutaConDecRec]
      ,[Recargo]
      ,[PrimaSinRecaDcto])

  select *
    from openquery(dataserver,'execute PROCEDURE sp_eco01(''01/01/2021'',''15/04/2021'')')