INSERT INTO bcoproc  VALUES ("01","DEPOSITOS","DP");
INSERT INTO bcoproc  VALUES ("02","NOTA DEBITO","ND");
INSERT INTO bcoproc  VALUES ("03","NOTA CREDITO","NC");
INSERT INTO bcoproc  VALUES ("04","CHEQUES","CK");
