-- proceso que realiza la modificacion de unidad en negativo tecnica de seguros

-- Creado: 11/08/2017 - Autor: Federico Coronado

drop procedure sp_end15;

create procedure "informix".sp_end15()
returning integer;


define _no_unidad_deivid		varchar(5);
define _no_factura_json			varchar(15);
define _prima					decimal(16,2);
define _prima_neta				decimal(16,2);
define _prima_bruta				decimal(16,2);
define _impuesto				decimal(16,2);
define _no_poliza_deivid        varchar(10);
define _no_factura_deivid	    varchar(15);
define _no_endoso_deivid        varchar(5);	
define _cnt_r                   integer;
define _renglon                 integer;
define _num_carga               varchar(6);

set isolation to dirty read;
--SET DEBUG FILE TO "sp_end15.trc"; 
--TRACE ON;
let _renglon = 0;
foreach
		select no_factura
		  into _no_factura_deivid
		  from facturas_duplicada
		 -- where no_factura in ('09-167066','09-167067')
		 -- where no_factura in ('09-159305','09-159306')

		select no_poliza, 
			   no_endoso 
		  into _no_poliza_deivid,
			   _no_endoso_deivid
		  from endedmae 
		 where no_factura = _no_factura_deivid;
		 
		 foreach
			 select no_unidad, 
					prima, 
					prima_neta, 
					impuesto, 
					prima_bruta
			   into _no_unidad_deivid, 
					_prima, 
					_prima_neta, 
					_impuesto, 
					_prima_bruta   
			   from endeduni
			  where no_poliza = _no_poliza_deivid 
				and no_endoso = _no_endoso_deivid

			select count(*)
			 into _cnt_r 			
			 FROM prdemielctdet
			where cod_agente  = '00180' 
			  and  no_unidad  = _no_unidad_deivid
			  and  proceso 	  = 'C'
			  and no_factura  = _no_factura_deivid;	
			  
			if _cnt_r > 0 then
			Insert Into prdemielctdet(
						no_documento, 
						cod_ramo, 
						vigencia_inic, 
						vigencia_final, 
						observaciones, 
						suma_asegurada, 
						no_unidad,  
						cedula, 
						pasaporte, 
						ruc, 
						cliente_nom, 
						cliente_ape, 
						cliente_ape_seg, 
						cliente_ape_casada, 
						tipo_persona, 
						fecha_aniversario, 
						sexo, estado_civil, 
						telefono1, 
						telefono2, 
						celular, 
						e_mail,
						direccion,
						direccion_cobros, 
						proceso, 
						prima_sin_desc, 
						descuento, 
						prima_neta, 
						porc_impuesto, 
						tot_impuesto, 
						prima_bruta, 
						fecha_primer_pago, 
						fecha_registro, 
						cod_formapag, 
						cod_perpago, 
						no_pagos,
						cod_agente,
						num_carga,
						renglon,
						cod_producto,
						no_poliza,
						actualizado,
						no_factura_tecnica,
						no_factura,
						saldo,
						saldo_con_impuesto,
						impuesto_saldo,
						prima_vida,
						suma_edificio,
						suma_contenido,
						mercancia_desde,
						mercancia_hasta,
						limite_lesiones1,
						limite_lesiones2,
						prima_danos,
						limite_danos1,
						limite_danos2,
						prima_gastos_med,
						limite_gastos_med1,
						limite_gastos_med2,
						prima_comprensivo,
						limite_comprensivo1,
						limite_comprensivo2,
						prima_colision,
						limite_colision1,
						limite_colision2,
						deducible_colision,
						otras_cob,
						prima_explosion,
						prima_terremoto,
						prima_vendabal,
						--prima_otros_incend,
						--prima_total_transp,
						--prima_total_otros_,
						porc_desc_tarjeta,
						tarjeta_descuento,
						desc_unidad)
			SELECT 	 first 1	no_documento, 
						cod_ramo, 
						vigencia_inic, 
						vigencia_final, 
						observaciones, 
						suma_asegurada, 
						_no_unidad_deivid, 
						cedula, 
						pasaporte, 
						ruc, 
						cliente_nom, 
						cliente_ape, 
						cliente_ape_seg, 
						cliente_ape_casada, 
						tipo_persona, 
						fecha_aniversario, 
						sexo, estado_civil, 
						telefono1, 
						telefono2, 
						celular, 
						e_mail,
						direccion,
						direccion_cobros, 
						'M', 
						_prima * -1, 
						descuento, 
						_prima_neta * -1, 
						5, 
						_impuesto * -1, 
						_prima_bruta * -1, 
						fecha_primer_pago, 
						fecha_registro, 
						cod_formapag, 
						cod_perpago, 
						no_pagos,
						cod_agente,
						num_carga,
						renglon,
						cod_producto,
						_no_poliza_deivid,
						0,
						no_factura_tecnica,
						no_factura,
						saldo,
						saldo_con_impuesto,
						impuesto_saldo,
						prima_vida,
						suma_edificio,
						suma_contenido,
						mercancia_desde,
						mercancia_hasta,
						limite_lesiones1,
						limite_lesiones2,
						prima_danos,
						limite_danos1,
						limite_danos2,
						prima_gastos_med,
						limite_gastos_med1,
						limite_gastos_med2,
						prima_comprensivo,
						limite_comprensivo1,
						limite_comprensivo2,
						prima_colision,
						limite_colision1,
						limite_colision2,
						deducible_colision,
						otras_cob,
						prima_explosion,
						prima_terremoto,
						prima_vendabal,
						--prima_otros_incend,
						--prima_total_transp,
						--prima_total_otros_,
						porc_desc_tarjeta,
						tarjeta_descuento,
						desc_unidad
			 FROM prdemielctdet
			where cod_agente  = '00180' 
			  and  no_unidad  = _no_unidad_deivid
			  and  proceso 	  = 'C'
			  and no_factura  = _no_factura_deivid;

			  
			  
			Insert Into prdemielctdet(
						no_documento, 
						cod_ramo, 
						vigencia_inic, 
						vigencia_final, 
						observaciones, 
						suma_asegurada, 
						no_unidad,  
						cedula, 
						pasaporte, 
						ruc, 
						cliente_nom, 
						cliente_ape, 
						cliente_ape_seg, 
						cliente_ape_casada, 
						tipo_persona, 
						fecha_aniversario, 
						sexo, estado_civil, 
						telefono1, 
						telefono2, 
						celular, 
						e_mail,
						direccion,
						direccion_cobros, 
						proceso, 
						prima_sin_desc, 
						descuento, 
						prima_neta, 
						porc_impuesto, 
						tot_impuesto, 
						prima_bruta, 
						fecha_primer_pago, 
						fecha_registro, 
						cod_formapag, 
						cod_perpago, 
						no_pagos,
						cod_agente,
						num_carga,
						renglon,
						cod_producto,
						no_poliza,
						actualizado,
						no_factura_tecnica,
						no_factura,
						saldo,
						saldo_con_impuesto,
						impuesto_saldo,
						prima_vida,
						suma_edificio,
						suma_contenido,
						mercancia_desde,
						mercancia_hasta,
						limite_lesiones1,
						limite_lesiones2,
						prima_danos,
						limite_danos1,
						limite_danos2,
						prima_gastos_med,
						limite_gastos_med1,
						limite_gastos_med2,
						prima_comprensivo,
						limite_comprensivo1,
						limite_comprensivo2,
						prima_colision,
						limite_colision1,
						limite_colision2,
						deducible_colision,
						otras_cob,
						prima_explosion,
						prima_terremoto,
						prima_vendabal,
						--prima_otros_incend,
						--prima_total_transp,
						--prima_total_otros_,
						porc_desc_tarjeta,
						tarjeta_descuento,
						desc_unidad)
			SELECT 	 first 1	no_documento, 
						cod_ramo, 
						vigencia_inic, 
						vigencia_final, 
						observaciones, 
						suma_asegurada, 
						_no_unidad_deivid, 
						cedula, 
						pasaporte, 
						ruc, 
						cliente_nom, 
						cliente_ape, 
						cliente_ape_seg, 
						cliente_ape_casada, 
						tipo_persona, 
						fecha_aniversario, 
						sexo, estado_civil, 
						telefono1, 
						telefono2, 
						celular, 
						e_mail,
						direccion,
						direccion_cobros, 
						'A', 
						_prima, 
						descuento, 
						_prima_neta, 
						5, 
						_impuesto, 
						_prima_bruta, 
						fecha_primer_pago, 
						fecha_registro, 
						cod_formapag, 
						cod_perpago, 
						no_pagos,
						cod_agente,
						num_carga,
						renglon + 1,
						cod_producto,
						_no_poliza_deivid,
						1,
						no_factura_tecnica,
						no_factura,
						saldo,
						saldo_con_impuesto,
						impuesto_saldo,
						prima_vida,
						suma_edificio,
						suma_contenido,
						mercancia_desde,
						mercancia_hasta,
						limite_lesiones1,
						limite_lesiones2,
						prima_danos,
						limite_danos1,
						limite_danos2,
						prima_gastos_med,
						limite_gastos_med1,
						limite_gastos_med2,
						prima_comprensivo,
						limite_comprensivo1,
						limite_comprensivo2,
						prima_colision,
						limite_colision1,
						limite_colision2,
						deducible_colision,
						otras_cob,
						prima_explosion,
						prima_terremoto,
						prima_vendabal,
						--prima_otros_incend,
						--prima_total_transp,
						--prima_total_otros_,
						porc_desc_tarjeta,
						tarjeta_descuento,
						desc_unidad
				 FROM prdemielctdet
				where cod_agente  = '00180' 
				  and  no_unidad  = _no_unidad_deivid
				  and  proceso 	  = 'C'
				  and no_factura  = _no_factura_deivid;
			else
			let _renglon = _renglon + 1;
			let _num_carga = "0000"||_renglon;
				Insert Into prdemielctdet(
						no_documento, 
						cod_ramo, 
						vigencia_inic, 
						vigencia_final, 
						observaciones, 
						suma_asegurada, 
						no_unidad,  
						cedula, 
						pasaporte, 
						ruc, 
						cliente_nom, 
						cliente_ape, 
						cliente_ape_seg, 
						cliente_ape_casada, 
						tipo_persona, 
						fecha_aniversario, 
						sexo, estado_civil, 
						telefono1, 
						telefono2, 
						celular, 
						e_mail,
						direccion,
						direccion_cobros, 
						proceso, 
						prima_sin_desc, 
						descuento, 
						prima_neta, 
						porc_impuesto, 
						tot_impuesto, 
						prima_bruta, 
						fecha_primer_pago, 
						fecha_registro, 
						cod_formapag, 
						cod_perpago, 
						no_pagos,
						cod_agente,
						num_carga,
						renglon,
						cod_producto,
						no_poliza,
						actualizado,
						no_factura_tecnica,
						no_factura,
						saldo,
						saldo_con_impuesto,
						impuesto_saldo,
						prima_vida,
						suma_edificio,
						suma_contenido,
						mercancia_desde,
						mercancia_hasta,
						limite_lesiones1,
						limite_lesiones2,
						prima_danos,
						limite_danos1,
						limite_danos2,
						prima_gastos_med,
						limite_gastos_med1,
						limite_gastos_med2,
						prima_comprensivo,
						limite_comprensivo1,
						limite_comprensivo2,
						prima_colision,
						limite_colision1,
						limite_colision2,
						deducible_colision,
						otras_cob,
						prima_explosion,
						prima_terremoto,
						prima_vendabal,
						--prima_otros_incend,
						--prima_total_transp,
						--prima_total_otros_,
						porc_desc_tarjeta,
						tarjeta_descuento,
						desc_unidad)
			SELECT 	 first 1	no_documento, 
						cod_ramo, 
						vigencia_inic, 
						vigencia_final, 
						observaciones, 
						suma_asegurada, 
						_no_unidad_deivid, 
						cedula, 
						pasaporte, 
						ruc, 
						cliente_nom, 
						cliente_ape, 
						cliente_ape_seg, 
						cliente_ape_casada, 
						tipo_persona, 
						fecha_aniversario, 
						sexo, estado_civil, 
						telefono1, 
						telefono2, 
						celular, 
						e_mail,
						direccion,
						direccion_cobros, 
						'M', 
						_prima * -1, 
						descuento, 
						_prima_neta * -1, 
						5, 
						_impuesto * -1, 
						_prima_bruta * -1, 
						fecha_primer_pago, 
						fecha_registro, 
						cod_formapag, 
						cod_perpago, 
						no_pagos,
						cod_agente,
						_num_carga,
						_renglon,
						cod_producto,
						_no_poliza_deivid,
						0,
						no_factura_tecnica,
						no_factura,
						saldo,
						saldo_con_impuesto,
						impuesto_saldo,
						prima_vida,
						suma_edificio,
						suma_contenido,
						mercancia_desde,
						mercancia_hasta,
						limite_lesiones1,
						limite_lesiones2,
						prima_danos,
						limite_danos1,
						limite_danos2,
						prima_gastos_med,
						limite_gastos_med1,
						limite_gastos_med2,
						prima_comprensivo,
						limite_comprensivo1,
						limite_comprensivo2,
						prima_colision,
						limite_colision1,
						limite_colision2,
						deducible_colision,
						otras_cob,
						prima_explosion,
						prima_terremoto,
						prima_vendabal,
						--prima_otros_incend,
						--prima_total_transp,
						--prima_total_otros_,
						porc_desc_tarjeta,
						tarjeta_descuento,
						desc_unidad
			 FROM prdemielctdet
			where cod_agente  = '00180' 
			  --and  no_unidad  = _no_unidad_deivid
			  and  proceso 	  = 'C'
			  and no_factura  = _no_factura_deivid;

			  
			  
			Insert Into prdemielctdet(
						no_documento, 
						cod_ramo, 
						vigencia_inic, 
						vigencia_final, 
						observaciones, 
						suma_asegurada, 
						no_unidad,  
						cedula, 
						pasaporte, 
						ruc, 
						cliente_nom, 
						cliente_ape, 
						cliente_ape_seg, 
						cliente_ape_casada, 
						tipo_persona, 
						fecha_aniversario, 
						sexo, estado_civil, 
						telefono1, 
						telefono2, 
						celular, 
						e_mail,
						direccion,
						direccion_cobros, 
						proceso, 
						prima_sin_desc, 
						descuento, 
						prima_neta, 
						porc_impuesto, 
						tot_impuesto, 
						prima_bruta, 
						fecha_primer_pago, 
						fecha_registro, 
						cod_formapag, 
						cod_perpago, 
						no_pagos,
						cod_agente,
						num_carga,
						renglon,
						cod_producto,
						no_poliza,
						actualizado,
						no_factura_tecnica,
						no_factura,
						saldo,
						saldo_con_impuesto,
						impuesto_saldo,
						prima_vida,
						suma_edificio,
						suma_contenido,
						mercancia_desde,
						mercancia_hasta,
						limite_lesiones1,
						limite_lesiones2,
						prima_danos,
						limite_danos1,
						limite_danos2,
						prima_gastos_med,
						limite_gastos_med1,
						limite_gastos_med2,
						prima_comprensivo,
						limite_comprensivo1,
						limite_comprensivo2,
						prima_colision,
						limite_colision1,
						limite_colision2,
						deducible_colision,
						otras_cob,
						prima_explosion,
						prima_terremoto,
						prima_vendabal,
						--prima_otros_incend,
						--prima_total_transp,
						--prima_total_otros_,
						porc_desc_tarjeta,
						tarjeta_descuento,
						desc_unidad)
			SELECT 	 first 1	no_documento, 
						cod_ramo, 
						vigencia_inic, 
						vigencia_final, 
						observaciones, 
						suma_asegurada, 
						_no_unidad_deivid, 
						cedula, 
						pasaporte, 
						ruc, 
						cliente_nom, 
						cliente_ape, 
						cliente_ape_seg, 
						cliente_ape_casada, 
						tipo_persona, 
						fecha_aniversario, 
						sexo, estado_civil, 
						telefono1, 
						telefono2, 
						celular, 
						e_mail,
						direccion,
						direccion_cobros, 
						'A', 
						_prima, 
						descuento, 
						_prima_neta, 
						5, 
						_impuesto, 
						_prima_bruta, 
						fecha_primer_pago, 
						fecha_registro, 
						cod_formapag, 
						cod_perpago, 
						no_pagos,
						cod_agente,
						_num_carga,
						_renglon,
						cod_producto,
						_no_poliza_deivid,
						1,
						no_factura_tecnica,
						no_factura,
						saldo,
						saldo_con_impuesto,
						impuesto_saldo,
						prima_vida,
						suma_edificio,
						suma_contenido,
						mercancia_desde,
						mercancia_hasta,
						limite_lesiones1,
						limite_lesiones2,
						prima_danos,
						limite_danos1,
						limite_danos2,
						prima_gastos_med,
						limite_gastos_med1,
						limite_gastos_med2,
						prima_comprensivo,
						limite_comprensivo1,
						limite_comprensivo2,
						prima_colision,
						limite_colision1,
						limite_colision2,
						deducible_colision,
						otras_cob,
						prima_explosion,
						prima_terremoto,
						prima_vendabal,
						--prima_otros_incend,
						--prima_total_transp,
						--prima_total_otros_,
						porc_desc_tarjeta,
						tarjeta_descuento,
						desc_unidad
				 FROM prdemielctdet
				where cod_agente  = '00180' 
				  --and  no_unidad  = _no_unidad_deivid
				  and  proceso 	  = 'C'
				  and no_factura  = _no_factura_deivid;
			end if
				update prdemielctdet
				   set actualizado = 0
				 where cod_agente  = '00180' 
			       and  no_unidad  = _no_unidad_deivid
			       and  proceso = 'C'
			       and no_factura  = _no_factura_deivid;
				return  0
					with resume;
		end foreach
	end foreach
end procedure