-- Procedimiento para crear en agtbitacora todos los registros de agentes nuevos y modificados
--
-- Creado    : 27/04/2006 - Autor: Amado Perez Mendoza 
--
-- SIS v.2.0 - DEIVID, S.A.

DROP PROCEDURE sp_par214;

CREATE PROCEDURE "informix".sp_par214(a_agente CHAR(10), a_tipo_mov CHAR(1))
 
define _username	char(32);

let _username = sp_sis84();

-- SET DEBUG FILE TO "sp_pro44.trc";      
-- TRACE ON;                                                                     

INSERT INTO agtbitacora(
	cod_agente,
	cod_vendedor,
	cod_cobrador,
	cod_compania,
	cod_sucursal,
	nombre,
	vida,
	general,
	fianzas,
	no_licencia,
	tipo_persona,
	repres_legal,
	direccion_1,
	direccion_2,
	telefono1,
	telefono2,
	celular,
	apartado,
	cedula,
	estatus_licencia,
	suspendido_desde,
	suspendido_hasta,
	fax,
	contacto,
	alias,
	tipo_agente,
	cobra_poliza,
	generar_cheque,
	fecha_ult_comis,
	saldo,
	user_added,
	date_added,
	e_mail,
	code_pais,
	code_provincia,
	code_ciudad,
	code_distrito,
	code_correg,
	digito_ver,
	aqente_grupo,
	ced_provincia,
	ced_inicial,
	ced_tomo,
	ced_folio,
	ced_asiento,
	ced_correcta,
	email_reclamo,
	agente_agrupado,
	tipo_pago,
	tipo_cuenta,
	cod_cuenta,
	cod_banco,
	adelanto_comis,
	user_changed,
	date_changed,
	estatus_agente,
	tipo_mov,
	fecha_modif
	)
	SELECT 	cod_agente,
			cod_vendedor,
			cod_cobrador,
			cod_compania,
			cod_sucursal,
			nombre,
			vida,
			general,
			fianzas,
			no_licencia,
			tipo_persona,
			repres_legal,
			direccion_1,
			direccion_2,
			telefono1,
			telefono2,
			celular,
			apartado,
			cedula,
			estatus_licencia,
			suspendido_desde,
			suspendido_hasta,
			fax,
			contacto,
			alias,
			tipo_agente,
			cobra_poliza,
			generar_cheque,
			fecha_ult_comis,
			saldo,
			user_added,
			date_added,
			e_mail,
			code_pais,
			code_provincia,
			code_ciudad,
			code_distrito,
			code_correg,
			digito_ver,
			aqente_grupo,
			ced_provincia,
			ced_inicial,
			ced_tomo,
			ced_folio,
			ced_asiento,
			ced_correcta,
			email_reclamo,
			agente_agrupado,
			tipo_pago,
			tipo_cuenta,
			cod_cuenta,
			cod_banco,
			adelanto_comis,
			_username,
			date_changed,
			estatus_agente,
			a_tipo_mov,
			current
	  FROM agtagent
	 WHERE cod_agente = a_agente; 	             


END PROCEDURE
