-- Procedimiento para crear en clibitacora todos los registros de clientes nuevos y modificados
--
-- Creado    : 13/09/2005 - Autor: Amado Perez Mendoza 
--
-- SIS v.2.0 - DEIVID, S.A.

DROP PROCEDURE sp_par163b;

--DROP TABLE clibitacora;

CREATE PROCEDURE "informix".sp_par163b(a_cliente CHAR(10), a_tipo_mov CHAR(1))

-- Crear la tabla
{CREATE TABLE cliclienbak(
cod_cliente          char(10),
cod_compania         char(3),
cod_sucursal         char(3),
cod_origen           char(3),
cod_grupo            char(5),
cod_clasehosp        char(3),
cod_espmedica        char(3),
cod_ocupacion        char(3),
cod_trabajo          char(3),
cod_actividad        char(3),
code_pais            char(3),
code_provincia       char(2),
code_ciudad          char(2),
code_distrito        char(2),
code_correg          char(5),
nombre               varchar(100),
nombre_razon         varchar(100),
direccion_1          varchar(50),
direccion_2          varchar(50),
apartado             char(20),
tipo_persona         char(1),
actual_potencial     char(1),
cedula               varchar(30),
telefono1            char(10),
telefono2            char(10),
e_mail               char(50),
fax                  char(10),
date_added           date,
user_added           char(8),
de_la_red            smallint,
mala_referencia      smallint,
desc_mala_ref        varchar(250),
fecha_aniversario    date,
sexo                 char(1),
digito_ver           char(2),
date_changed         date,
user_changed         char(8),
nombre_original      char(100),
ced_provincia        char(2),
ced_inicial          char(2),
ced_tomo             char(6),
ced_folio            char(6),
ced_asiento          char(6),
aseg_primer_nom      char(100),
aseg_segundo_nom     char(40),
aseg_primer_ape      char(40),
aseg_segundo_ape     char(40),
aseg_casada_ape      char(40),
ced_correcta         smallint,
pasaporte            smallint,
cotizacion           char(10),
de_cotizacion        smallint,
celular              char(10),
dia_cobros1          integer,
dia_cobros2          integer,
contacto             char(50),
telefono3            char(10),
direccion_cob        varchar(100),
es_taller            smallint,
proveedor_autorizado   smallint,
ip_number            char(30)
);
}
-- SET DEBUG FILE TO "sp_pro44.trc";      
-- TRACE ON;                                                                     

INSERT INTO cliclienbak(
	cod_cliente,       
	cod_compania,      
	cod_sucursal,      
	cod_origen,        
	cod_grupo,         
	cod_clasehosp,     
	cod_espmedica,     
	cod_ocupacion,     
	cod_trabajo,       
	cod_actividad,     
	code_pais,         
	code_provincia,    
	code_ciudad,       
	code_distrito,     
	code_correg,       
	nombre,            
	nombre_razon,      
	direccion_1,       
	direccion_2,       
	apartado,          
	tipo_persona,      
	actual_potencial,  
	cedula,            
	telefono1,         
	telefono2,         
	e_mail,            
	fax,               
	date_added,        
	user_added,        
	de_la_red,         
	mala_referencia,   
	desc_mala_ref,     
	fecha_aniversario, 
	sexo,              
	digito_ver,        
	date_changed,      
	user_changed,      
	nombre_original,   
	ced_provincia,     
	ced_inicial,       
	ced_tomo,          
	ced_folio,         
	ced_asiento,       
	aseg_primer_nom,   
	aseg_segundo_nom,  
	aseg_primer_ape,   
	aseg_segundo_ape,  
	aseg_casada_ape,   
	ced_correcta,      
	pasaporte,         
	cotizacion,        
	de_cotizacion,     
	celular,           
	dia_cobros1,       
	dia_cobros2,       
	contacto,          
	telefono3,         
	direccion_cob,     
	es_taller,         
	proveedor_autorizado,
	ip_number
	)
	SELECT cod_cliente,       
		   cod_compania,      
		   cod_sucursal,      
		   cod_origen,        
		   cod_grupo,         
		   cod_clasehosp,     
		   cod_espmedica,     
		   cod_ocupacion,     
		   cod_trabajo,       
		   cod_actividad,     
		   code_pais,         
		   code_provincia,    
		   code_ciudad,       
		   code_distrito,     
		   code_correg,       
		   nombre,            
		   nombre_razon,      
		   direccion_1,       
		   direccion_2,       
		   apartado,          
		   tipo_persona,      
		   actual_potencial,  
		   cedula,            
		   telefono1,         
		   telefono2,         
		   e_mail,            
		   fax,               
		   date_added,        
		   user_added,        
		   de_la_red,         
		   mala_referencia,   
		   desc_mala_ref,     
		   fecha_aniversario, 
		   sexo,              
		   digito_ver,        
		   date_changed,      
		   user_changed,      
		   nombre_original,   
		   ced_provincia,     
		   ced_inicial,       
		   ced_tomo,          
		   ced_folio,         
		   ced_asiento,       
		   aseg_primer_nom,   
		   aseg_segundo_nom,  
		   aseg_primer_ape,   
		   aseg_segundo_ape,  
		   aseg_casada_ape,   
		   ced_correcta,      
		   pasaporte,         
		   cotizacion,        
		   de_cotizacion,     
		   celular,           
		   dia_cobros1,       
		   dia_cobros2,       
		   contacto,          
		   telefono3,         
		   direccion_cob,     
	 	   es_taller,         
		   proveedor_autorizado,
		   ip_number
	  FROM cliclien;
--	 WHERE cod_cliente = a_cliente; 	             


END PROCEDURE
