create procedure sp_create_endedtri()

create table endedtri(
	no_poliza				char(10),
	no_endoso				char(5),
	cod_compania			char(3),
	cod_sucursal			char(3),
	cod_tipocalc			char(3),
	cod_formapag			char(3),
	cod_tipocan				char(3),
	cod_perpago				char(3),
	cod_endomov				char(3),
	no_documento			char(20),
	vigencia_inic			date,
	vigencia_final			date,
	prima					dec(16,2),
	descuento				dec(16,2),
	recargo					dec(16,2),
	prima_neta				dec(16,2),
	impuesto				dec(16,2),
	prima_bruta				dec(16,2),
	prima_suscrita			dec(16,2),
	prima_retenida			dec(16,2),
	tiene_impuesto			smallint,
	fecha_emision			date,
	fecha_impresion			date,
	fecha_primer_pago		date,
	no_pagos				smallint,
	actualizado				smallint,
	no_factura				char(10),
	fact_reversar			char(10),
	date_added				date,
	date_changed			date,
	interna					smallint,
	periodo					char(7),
	user_added				char(8),
	factor_vigencia			dec(9,6),
	suma_asegurada			dec(16,2),
	posteado				char(1),
	activa					smallint,
	vigencia_inic_pol		date,
	vigencia_final_pol		date,
	no_endoso_ext			char(5)
	);

end procedure