
--tablas de producion
SELECT * FROM TMP_DET_MOVIM_TECNICO_PRI     --1
SELECT * FROM TMP_DET_MOVIM_REASEGURO_PRI   --2
SELECT * FROM TMP_DET_REASEGURO_CARACT_PRI  --3
 
--tablas de cobros
SELECT * FROM TMP_DET_MOVIM_TECNICO_PRI_COB  --1 
SELECT * FROM TMP_DET_MOVIM_REASEGURO_PRI_C  --2
SELECT * FROM TMP_DET_REASEGURO_CARACT_PRI_C --3 

--tabla de cheques 
SELECT * FROM TMP_CHEQUES          --1
SELECT * FROM TMP_CHEQUES_AUX      --2

--tabla de cuentas 
SELECT * FROM TMP_CGLRESUMEN  --1
SELECT * FROM TMP_CGLRESUMEN1 --2

